version: '3.4'

services:
  migrations:
    build:
      context: ../../
      dockerfile: templates/service/database/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - IdentityServer_DB=announcements_backend_Identity
      - announcements_backend_DB=announcements_backend_ModuleDb
      - SA_PASSWORD=yourStrong(!)Password
